version: '3'

services:
 app:
  build: ./app
  ports:
   - "5000:5000"
  environment:
   - HOST=db
  links:
   - db
  depends_on:
   - db
 db:
  image: mysql:5.7
  volumes:
   - ./db:/docker-entrypoint-initdb.d/:ro
  environment:
   - MYSQL_DATABASE=career_path_db
   - MYSQL_USER=career_path
   - MYSQL_ROOT_PASSWORD=my-secret-pw
   - MYSQL_PASSWORD=career_path_pwd
